---
version: 1.0.0
hassio_api: true
slug: nginx_advanced
name: NGINX Home Assistant SSL proxy with advanced configuration
description: "An SSL/TLS proxy with only one line of nginx config: include /shared/nginx_advanced.conf"
url: https://github.com/janmagnusdev/ha-addon-nginx-advanced/tree/main/nginx_advanced
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: janmagnusdev/{arch}-addon-nginx_advanced
init: false
map:
  - ssl
  - share
options:
  domain: null
  hsts: max-age=31536000; includeSubDomains
  certfile: fullchain.pem
  keyfile: privkey.pem
  cloudflare: false
  customize:
    active: false
    default: nginx_proxy_default*.conf
    servers: nginx_proxy/*.conf
  real_ip_from: []
ports:
  443/tcp: 443
  80/tcp: null
schema:
  domain: str
  hsts: str
  certfile: str
  keyfile: str
  cloudflare: bool
  customize:
    active: bool
    default: str
    servers: str
  real_ip_from:
    - str
