---
version: 1.0.0
hassio_api: true
slug: nginx_advanced
name: NGINX Advanced
description: "An NGINX addon for powerusers"
url: https://github.com/janmagnusdev/ha-addon-nginx-advanced/tree/main/nginx_advanced
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: janmagnusdev/{arch}-addon-nginx_advanced
init: false
map:
  - ssl
  - share
options:
  config_file: nginx_advanced.conf
ports:
  443/tcp: 443
  80/tcp: null
schema:
  config_file: "str"
